### ISSUE TITLE
All Bintray services will be deprecated and your accounts will be disabled on May 1st 2021. 

### ISSUE THREAD

**Issue by SimonIT** [spookygames/gdx-notifications#9]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ @arthurtemple

**Comment by arthurtemple** [comment]
Thanks for the heads up.

Coming late to the game but it will be handled before the deadline.

**Comment by arthurtemple** [comment]
Artifacts are now available on Maven Central. Unfortunately I had to change the group, from `net.spookygames` to `games.spooky`.

You have now two options:
* Use `games.spooky.gdx:gdx-notifications:0.1.0`, your code should not need any modification.
* Use `games.spooky.gdx:gdx-notifications:1.0.0`, and you should adjust all imports to use package `games.spooky.gdx.notifications` instead of `net.spookygames.gdx.notifications`.

Future artifacts will feature code under package `games.spooky.gdx.notifications`.

Please re-open this issue if you are unhappy with the change.
